config/routes.rb
Rails.application.routes.draw do
root "home#index"

resources :products

get "/product/:id/buy", to: "products#buy", as: "buy"

get "/checkout", to: "products#checkout", as: "checkout"

get 'products.json', to: 'products#list'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end
  

app/models/product.rb
class Product < ApplicationRecord
    #include Visible

    validates :title, presence: true
    validates :description, presence: true
    #validates :seller, presence: true
    validates :left, comparison: {greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if session[:cart].nil?
        session[:cart] = []
    end
    
    @products = Product.all
    @cart = session[:cart]
  end

  def list
    # return products as json list
    @products = Product.all
    render json: @products
  end
  
  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path, status: :see_other
  end

  def buy
    if session[:cart].nil?
      session[:cart] = []
    end
      @product = Product.find(params[:id])
      session[:cart].append(@product)
      redirect_to root_path

  end

  def checkout
      @cart = session[:cart]
      @cart.each do |product|
        @product = Product.find(product["id"])
        @product.left = @product.left-1
        @product.save
      end
      #Empty the shopping cart
      session[:cart] = []
  end


  private
    def product_params
      params.require(:product).permit(:title,:description,:seller, :price, :status, :left)

    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rigdome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
  <div>
    <b><%= form.label :title %><br></b>
    <%= form.text_field :title %>
    <% product.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <b><%= form.label :description %><br></b>
    <%= form.text_area :description %><br>
    <% product.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <b><%= form.label :price %><br></b>
    <%= form.text_field :price %><br>
    <% product.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <b><%= form.label :image %><br></b>
    <%= form.text_area :image %><br>
    <% product.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="d-grid">
    <button class="btn btn-primary" type="button"><%= form.submit %></button>
  </div>

  <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

<% end %>

app/views/products/checkout.html.erb
<h2> Your shopping cart has <%=@cart.length%> items</h2>

<p>Your cart consists of the following: </p>

<ul>
  <% @cart.each do |product| %>
    <li> <%=product["title"]%> </li>
  <% end %>
</ul>

<p> Your item will be on the way! Thank you for shopping with us!! </p>

<%= link_to "Main Page", root_path, class:"btn btn-outline-primary" %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>Products</h1>



<ul>
 
  <% @products.each do |product| %>
    <div class="list-group">
    <li>
      <a href="#" class="list-group-item list-group-item-action active" aria-current="true">
      <%= link_to product.title, product%>
      </a>
      <%= image_tag product.image, width: 100, height: 100 %>
      <%= product.left %>
      <%= link_to "Buy Now", buy_path(product) %>
      
    </li>
    </div>
  <% end %>
  
</ul>



<%= link_to "New Product", new_product_path, class:"btn btn-outline-primary"%>

<%= link_to "Check Out", checkout_path, class:"btn btn-outline-primary" %>

<%= link_to "Main Page", root_path, class:"btn btn-outline-primary" %>

<h2> Your shopping cart has <%=@cart.length%> items</h2>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>

<p><%= @product.description %></p>

<p>$<%= @product.price %>0</p>




<ul>
  <%= link_to "Edit", edit_product_path(@product), class:"btn btn-secondary" %>
  <%= link_to "Destroy", product_path(@product), class:"btn btn-danger", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure you want to delete this listing?"
                  } %>
  <%= link_to "Back to Current Listings", products_path, class:"btn btn-outline-success" %>
</ul>